### ISSUE TITLE
How to save image with graphic overlay

### ISSUE THREAD

**Issue by reaurr** [AccordionGuy/FaceSpotter#1]
Hi,
I've try to save image with graphic overlay but could not success. It save only pure image with out any graphics. 
How can we solve it?

**Comment by AccordionGuy** [comment]
Hello, drojokef! I just saw that you opened, then closed the issue. If you have a solution, I’d love to see it.

**Comment by rehantu** [comment]
Hello, drojokef! I just saw that you opened, then closed the issue. If you have a solution, I’d love to see it.
